### 建立報名
POST http://localhost:3001/api/signup
Content-Type: application/json

{
  "name": "新同學",
  "email": "new@example.com",
  "phone": "0911222333"
}

### 確認是否返回成功
Send Request
GET http://localhost:3001/api/signup

### 更新
PATCH http://localhost:3001/api/signup/{{last_id}}
Content-Type: application/json

{
  "phone": "0911000111"
}


### 刪除
DELETE http://localhost:3001/api/signup/{{last_id}}
